### ISSUE TITLE
Plugin Completely Not working

### ISSUE THREAD

**Issue by EamonnR** [francoiscote/acf-field-tweet#1]
Hi,

I have included this plugin on my WordPress install with ACF5 but I'm not seeing any results coming back on the Front End.

If I do a print_r on the object being returned - the [tweet_id] object returns the URL provided but the [raw_json] and [tweet_data] do not include any information. 

Do you have an example of how this plugin extension should work when configured correctly?

Thanks.

**Comment by francoiscote** [comment]
Better late than never, I guess.

I just retested this plugin with ACF PRO 5.3.6.1 and it seems to work fine.

Make sure you only put the Tweet ID in the `tweet_id` field, and not the full URL.
